packages = [
  "nltk",
]

[[fetch]]
from = "https://raw.githubusercontent.com/pbizopoulos/naming-convention/main/python/python/main.py"

[[fetch]]
from = "https://raw.githubusercontent.com/pbizopoulos/naming-convention/main/python/prm/test_function.py"

[[fetch]]
from = "https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/tokenizers/punkt.zip"

